services:
  - type: web
    name: todo-frontend-vexg
    runtime: static
    rootDir: frontend/crud_frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
